
path: /home/ravin/catkin_ws/src/turtlebot3_autorace_HSA22/turtlebot3_autorace_detect/nodes  # dataset root dir
train: images  # train images (relative to 'path')
val: images  # val images (relative to 'path')

# Classes
names:
  0: tunnel
  1: Speedlimit_50
  2: Speedlimit_100
  3: intersection
  4: parking
  5: right
  6: left
  7: construction
  8: stop
  9: traffic_light
  
